# Generated by Django 4.2.7 on 2026-05-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=80, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("modulo", models.CharField(db_index=True, max_length=50)),
                ("descripcion", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
                "db_table": "permisos",
                "ordering": ["modulo", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, unique=True)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("activo", models.BooleanField(default=True)),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, el rol no se puede borrar ni editar sus permisos.",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "permisos",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="permisos.permiso"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["nombre"],
            },
        ),
    ]
