# Generated by Django 4.2.7 on 2026-05-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permisos", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="permisos_directos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permisos otorgados directamente al usuario, adicionales a los del rol.",
                related_name="usuarios",
                to="permisos.permiso",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Roles asignados al usuario (suma de permisos).",
                related_name="usuarios",
                to="permisos.rol",
            ),
        ),
    ]
