# Generated by Django 6.0.3 on 2026-03-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cedula de Ciudadania"),
                            ("TI", "Tarjeta de Identidad"),
                            ("CE", "Cedula de Extranjeria"),
                            ("PA", "Pasaporte"),
                            ("RC", "Registro Civil"),
                        ],
                        max_length=2,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=20, unique=True)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, default="", max_length=20)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "db_table": "pacientes",
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
