# Generated by Django 6.0.3 on 2026-04-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="apellidos",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nombres",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="numero_documento",
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CC", "Cedula de Ciudadania"),
                    ("TI", "Tarjeta de Identidad"),
                    ("CE", "Cedula de Extranjeria"),
                    ("PA", "Pasaporte"),
                    ("RC", "Registro Civil"),
                    ("PPT", "Permiso de Protección Temporal"),
                    ("MIL", "Correo electrónico (sin documento)"),
                    ("TEL", "Teléfono / Celular (sin documento)"),
                    ("SIN", "Sin identificar"),
                ],
                max_length=3,
            ),
        ),
    ]
