# Generated by Django 6.0.3 on 2026-05-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0002_alter_paciente_apellidos_alter_paciente_nombres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Correo electrónico de contacto (alternativa al teléfono).",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="nombre_autorizado",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre de la persona autorizada cuando el teléfono no es del paciente.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="telefono_pertenece_a",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paciente", "Del paciente"),
                    ("autorizado", "De persona autorizada"),
                ],
                default="",
                help_text="Indica si el teléfono es del paciente o de una persona autorizada.",
                max_length=20,
            ),
        ),
    ]
