# Generated by Django 6.0.3 on 2026-03-16 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SOLICITADA", "Solicitada"),
                            ("EN_BUSQUEDA", "En busqueda"),
                            ("LISTA", "Lista"),
                            ("ENTREGADA", "Entregada"),
                        ],
                        default="SOLICITADA",
                        max_length=20,
                    ),
                ),
                ("motivo", models.TextField()),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_lista", models.DateTimeField(blank=True, null=True)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                (
                    "entregado_a",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("observaciones", models.TextField(blank=True, default="")),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud",
                "verbose_name_plural": "Solicitudes",
                "db_table": "solicitudes",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
