# Generated by Django 6.0.3 on 2026-04-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitudes", "0003_add_campos_solicitud"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="archivo_hc",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="historias_clinicas/",
                verbose_name="Archivo PDF de la HC",
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="atencion_hasta_la_fecha",
            field=models.BooleanField(default=False, verbose_name="Hasta la fecha"),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="envio_canal",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="envio_destinatario",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="envio_estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDIENTE", "Pendiente de envío"),
                    ("ENVIADO", "Enviada al paciente"),
                    ("ERROR", "Error al enviar"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="envio_fecha",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="envio_mensaje",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="fecha_atencion_desde",
            field=models.DateField(
                blank=True, null=True, verbose_name="Atención desde"
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="fecha_atencion_hasta",
            field=models.DateField(
                blank=True, null=True, verbose_name="Atención hasta"
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="hora_recibo",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora recibo (cuando entró)"
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="hosvital_estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_PROCESO", "En proceso"),
                    ("RECIBIDA", "Recibida (PDF disponible)"),
                    ("ERROR", "Error al consultar Hosvital"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="hosvital_fecha",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="hosvital_mensaje",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="fechas_atencion",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                verbose_name="Fechas de atención (texto)",
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="hora_envio",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Hora envío (cuando se entregó)"
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="tipo_doc_autorizado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("TI", "Tarjeta de Identidad"),
                    ("CE", "Cédula de Extranjería"),
                    ("PA", "Pasaporte"),
                    ("RC", "Registro Civil"),
                    ("PPT", "Permiso de Protección Temporal"),
                ],
                default="",
                max_length=3,
            ),
        ),
    ]
