# Generated by Django 6.0.3 on 2026-04-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitudes", "0004_solicitud_archivo_hc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitud",
            name="motivo_solicitud",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Motivo de la solicitud (texto libre)",
            ),
        ),
    ]
