# Generated by Django 6.0.3 on 2026-05-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitudes", "0005_alter_solicitud_motivo_solicitud"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumentoSolicitado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de documento solicitado",
                "verbose_name_plural": "Tipos de documento solicitado",
                "db_table": "tipos_documento_solicitado",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="documento_solicitado",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
