# Generated by Django 6.0.3 on 2026-05-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitudes", "0006_tipodocumentosolicitado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parentesco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parentesco",
                "verbose_name_plural": "Parentescos",
                "db_table": "parentescos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumentoIdentidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Sigla: CC, TI, CE, etc.", max_length=10, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo del tipo de documento.",
                        max_length=120,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de documento de identidad",
                "verbose_name_plural": "Tipos de documento de identidad",
                "db_table": "tipos_documento_identidad",
                "ordering": ["nombre"],
            },
        ),
    ]
