# Generated by Django 6.0.3 on 2026-03-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("modelo_afectado", models.CharField(max_length=50)),
                ("registro_id", models.IntegerField()),
                ("detalle", models.TextField(blank=True, default="")),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de cambio",
                "verbose_name_plural": "Bitacora de cambios",
                "db_table": "bitacora",
                "ordering": ["-fecha"],
            },
        ),
    ]
